---
title: "Partner Organisations"
---

**Links to relevant partner organisations**
Here are some links to relevant partner organisations you might be interested in visiting. We will continue to add to them, so if you have any you think we should include, please do just get in touch.

__Relevant Organisations:__

* [Fire Magazine](https://www.fire-magazine.com)
* [WL Gore](https://www.gore.com)
* [Institution of Fire Engineers](http://www.ife.org.uk/)
* [Nottingham Trent University: Dr Rowena Hill](https://www.ntu.ac.uk/staff-profiles/social-sciences/rowena-hill)
* [West Midlands Fire Service](https://www.wmfs.net/)

__Sources of Funding for Research:__

* [The Fire Research and Training Trust](http://www.firetrust.info/)
* [The Economic and Social Research Council](http://www.esrc.ac.uk/)
* [The Engineering and Physical Sciences Research Council](https://www.epsrc.ac.uk/)
* [The National Lottery](https://www.lotterygoodcauses.org.uk/funding)
* [The Joseph Rowntree Foundation](https://www.jrf.org.uk/)

__Information on Quality Assurance in Research:__

* [Pathways to Impactful Research](http://www.rcuk.ac.uk/innovation/impacts/)

__Research Strategy:__

* [The National Fire Chiefs Council](https://www.nationalfirechiefs.org.uk/)
* [The National Police Chiefs Council](http://www.npcc.police.uk/Home.aspx)
* [Association of Ambulance Chief Executives](https://aace.org.uk/)

 